import 'package:kind_bridge/common/donation_item.dart';

final List<DonationItem> dummyDonations = [
  DonationItem(
    id: 'don1',
    donorId: 'donor01',
    name: 'Winter Jacket',
    category: 'Clothes',
    description: 'Warm jacket, gently used, size M',
    quantity: 2,
    condition: 'Gently Used',
    latitude: 8.8858112,
    longitude: 38.8101998,
    status: 'Available',
    ngoId: null,
    // imageUrl: 'https://example.com/images/jacket.png',
    createdAt: DateTime.now().subtract(Duration(days: 1)),
  ),
  DonationItem(
    id: 'don2',
    donorId: 'donor02',
    name: 'Canned Beans',
    category: 'Food',
    description: 'Pack of 12 cans',
    quantity: 12,
    condition: 'New',
    latitude: 8.8858613,
    longitude: 38.8104686,
    status: 'Available',
    ngoId: null,
    imageUrl: 'https://example.com/images/beans.png',
    createdAt: DateTime.now().subtract(Duration(days: 2)),
  ),
  DonationItem(
    id: 'don3',
    donorId: 'donor03',
    name: 'Laptop',
    category: 'Electronics',
    description: 'Dell Inspiron, lightly used, working condition',
    quantity: 1,
    condition: 'Used',
    latitude: 8.8858312,
    longitude: 38.8102298,
    status: 'Accepted',
    ngoId: 'ngo01',
    imageUrl: 'https://example.com/images/laptop.png',
    createdAt: DateTime.now().subtract(Duration(days: 3)),
  ),
  DonationItem(
    id: 'don4',
    donorId: 'donor04',
    name: 'School Backpack',
    category: 'Clothes & Accessories',
    description: 'Brand new, blue color',
    quantity: 5,
    condition: 'New',
    latitude: 8.8857812,
    longitude: 38.8101698,
    status: 'Available',
    ngoId: null,
    imageUrl: 'https://example.com/images/backpack.png',
    createdAt: DateTime.now().subtract(Duration(days: 1, hours: 5)),
  ),
  DonationItem(
    id: 'don5',
    donorId: 'donor05',
    name: 'Cooking Oil',
    category: 'Food',
    description: '2 liters, unopened',
    quantity: 10,
    condition: 'New',
    latitude: 8.8858512,
    longitude: 38.8102598,
    status: 'Available',
    ngoId: null,
    imageUrl: 'https://example.com/images/oil.png',
    createdAt: DateTime.now().subtract(Duration(hours: 12)),
  ),
];
